server:
    port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: paymentExchange
          content-type: application/json
          binder: defaultRabbit
  datasource:
    type: 
    url: jdbc:mysql://localhost/springclouddb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

feign:
  hystrix:
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bitforce.cloud.entities
