server:
    port: 3001

spring:
  application:
    name: cloud-config-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    config:
      server:
        git:
          uri: git@github.com:GuanyiLi-Craig/springcloudtest-config.git
          search-paths: 
            - springcloudtest-config
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "refresh-bus"